<?php

/**
 * Generates HTML table for TemporalItemStores
 *
 * @copyright 2015 Ethan Smith
 */

class ItemStoreTableFormatter {

   /**
    * Creates a table where each item is represented by a row
    * generated by the field formatter.
    *
    * @param $items array - array with the items to display
    * @param $fieldFormatter EntryFormatOutput - formatter for objects in $items
    * @param $header array - optional list of strings for header fields
    */
   public function buildListTableOfEntries($items, $fieldFormatter, $header = null) {
      $table = new TableElement();

      if ($header) {
         $table->addRow($header);
      }

      array_walk($items, function ($item) use ($table, $fieldFormatter) {
         $table->addRow($fieldFormatter->formatObject($item));
      });

      return $table->exportTableAsHTML();
   }


   public function buildTableByTimePeriod($itemStores, $timePeriods, $fieldFormatter, $header = null, $showsRowLabel = true) {
      $table = new TableElement();

      if ($header) {
         $table->addRow($header);
      }

      $self = $this;
      $table = array_reduce(array_keys($itemStores), function ($table, $name) use ($self, $fieldFormatter, $timePeriods, $itemStores, $showsRowLabel) {
         $items = $itemStores[$name]->generateValueSummary($fieldFormatter, $timePeriods);

         $self->addLabelToItems($items, $showsRowLabel, $name);
         $table->addRow($items);
         return $table;
      }, $table);

      return $table->exportTableAsHTML();
   }


   /**
    * Appends a label to the item array if we should force having label or
    * there is a label defined. We won't add a label in the case of no label
    * data and the label is not forced.
    *
    * @param &$items array - array with the items. may be added to.
    * @param $showsLabel boolean - should a label be shown
    * @param $name string - string for the label
    */
   public function addLabelToItems(&$items, $showsLabel, $name = null) {
      $label = $showsLabel ? $name : null;
      $label = $showsLabel && !$label ? '' : $label;

      if ($label || is_string($label)) {
         array_unshift($items, $label);
      }
   }
}
